version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "prettier"
  - package-ecosystem: "npm"
    directory: "packages/opa-react"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "prettier"
      react:
        patterns:
          - "@react/*"
          - "react*"
