version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/opa-react/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      eslint:
        patterns:
          - "@typescript-eslint/*"
          - "eslint-*"
          - "eslint"
          - "prettier"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
