/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { remap as remap$ } from "../../../lib/primitives.js";
import * as components from "../components/index.js";
import * as z from "zod";

/**
 * The input document
 */
export type ExecutePolicyWithInputRequestBody = {
    /**
     * Arbitrary JSON used within your policies by accessing `input`
     */
    input: components.Input;
};

export type ExecutePolicyWithInputRequest = {
    /**
     * The path separator is used to access values inside object and array documents. If the path indexes into an array, the server will attempt to convert the array index to an integer. If the path element cannot be converted to an integer, the server will respond with 404.
     */
    path?: string | undefined;
    /**
     * Indicates that the request body is gzip encoded
     */
    contentEncoding?: components.GzipContentEncoding | undefined;
    /**
     * Indicates the server should respond with a gzip encoded body. The server will send the compressed response only if its length is above `server.encoding.gzip.min_length` value. See the configuration section
     */
    acceptEncoding?: components.GzipAcceptEncoding | undefined;
    /**
     * If parameter is `true`, response will formatted for humans.
     */
    pretty?: boolean | undefined;
    /**
     * If parameter is true, response will include build/version info in addition to the result.
     */
    provenance?: boolean | undefined;
    /**
     * Return query explanation in addition to result.
     */
    explain?: components.Explain | undefined;
    /**
     * Return query performance metrics in addition to result.
     */
    metrics?: boolean | undefined;
    /**
     * Instrument query evaluation and return a superset of performance metrics in addition to result.
     */
    instrument?: boolean | undefined;
    /**
     * Treat built-in function call errors as fatal and return an error immediately.
     */
    strictBuiltinErrors?: boolean | undefined;
    /**
     * The input document
     */
    requestBody: ExecutePolicyWithInputRequestBody;
};

export type ExecutePolicyWithInputResponse = {
    httpMeta: components.HTTPMetadata;
    /**
     * Success.
     *
     * @remarks
     * The server also returns 200 if the path refers to an undefined document. In this case, the response will not contain a result property.
     *
     */
    successfulPolicyResponse?: components.SuccessfulPolicyResponse | undefined;
    headers: { [k: string]: Array<string> };
};

/** @internal */
export const ExecutePolicyWithInputRequestBody$inboundSchema: z.ZodType<
    ExecutePolicyWithInputRequestBody,
    z.ZodTypeDef,
    unknown
> = z.object({
    input: components.Input$inboundSchema,
});

/** @internal */
export type ExecutePolicyWithInputRequestBody$Outbound = {
    input: components.Input$Outbound;
};

/** @internal */
export const ExecutePolicyWithInputRequestBody$outboundSchema: z.ZodType<
    ExecutePolicyWithInputRequestBody$Outbound,
    z.ZodTypeDef,
    ExecutePolicyWithInputRequestBody
> = z.object({
    input: components.Input$outboundSchema,
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutePolicyWithInputRequestBody$ {
    /** @deprecated use `ExecutePolicyWithInputRequestBody$inboundSchema` instead. */
    export const inboundSchema = ExecutePolicyWithInputRequestBody$inboundSchema;
    /** @deprecated use `ExecutePolicyWithInputRequestBody$outboundSchema` instead. */
    export const outboundSchema = ExecutePolicyWithInputRequestBody$outboundSchema;
    /** @deprecated use `ExecutePolicyWithInputRequestBody$Outbound` instead. */
    export type Outbound = ExecutePolicyWithInputRequestBody$Outbound;
}

/** @internal */
export const ExecutePolicyWithInputRequest$inboundSchema: z.ZodType<
    ExecutePolicyWithInputRequest,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        path: z.string().default(""),
        "Content-Encoding": components.GzipContentEncoding$inboundSchema.optional(),
        "Accept-Encoding": components.GzipAcceptEncoding$inboundSchema.optional(),
        pretty: z.boolean().optional(),
        provenance: z.boolean().optional(),
        explain: components.Explain$inboundSchema.optional(),
        metrics: z.boolean().optional(),
        instrument: z.boolean().optional(),
        "strict-builtin-errors": z.boolean().optional(),
        RequestBody: z.lazy(() => ExecutePolicyWithInputRequestBody$inboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            "Content-Encoding": "contentEncoding",
            "Accept-Encoding": "acceptEncoding",
            "strict-builtin-errors": "strictBuiltinErrors",
            RequestBody: "requestBody",
        });
    });

/** @internal */
export type ExecutePolicyWithInputRequest$Outbound = {
    path: string;
    "Content-Encoding"?: string | undefined;
    "Accept-Encoding"?: string | undefined;
    pretty?: boolean | undefined;
    provenance?: boolean | undefined;
    explain?: string | undefined;
    metrics?: boolean | undefined;
    instrument?: boolean | undefined;
    "strict-builtin-errors"?: boolean | undefined;
    RequestBody: ExecutePolicyWithInputRequestBody$Outbound;
};

/** @internal */
export const ExecutePolicyWithInputRequest$outboundSchema: z.ZodType<
    ExecutePolicyWithInputRequest$Outbound,
    z.ZodTypeDef,
    ExecutePolicyWithInputRequest
> = z
    .object({
        path: z.string().default(""),
        contentEncoding: components.GzipContentEncoding$outboundSchema.optional(),
        acceptEncoding: components.GzipAcceptEncoding$outboundSchema.optional(),
        pretty: z.boolean().optional(),
        provenance: z.boolean().optional(),
        explain: components.Explain$outboundSchema.optional(),
        metrics: z.boolean().optional(),
        instrument: z.boolean().optional(),
        strictBuiltinErrors: z.boolean().optional(),
        requestBody: z.lazy(() => ExecutePolicyWithInputRequestBody$outboundSchema),
    })
    .transform((v) => {
        return remap$(v, {
            contentEncoding: "Content-Encoding",
            acceptEncoding: "Accept-Encoding",
            strictBuiltinErrors: "strict-builtin-errors",
            requestBody: "RequestBody",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutePolicyWithInputRequest$ {
    /** @deprecated use `ExecutePolicyWithInputRequest$inboundSchema` instead. */
    export const inboundSchema = ExecutePolicyWithInputRequest$inboundSchema;
    /** @deprecated use `ExecutePolicyWithInputRequest$outboundSchema` instead. */
    export const outboundSchema = ExecutePolicyWithInputRequest$outboundSchema;
    /** @deprecated use `ExecutePolicyWithInputRequest$Outbound` instead. */
    export type Outbound = ExecutePolicyWithInputRequest$Outbound;
}

/** @internal */
export const ExecutePolicyWithInputResponse$inboundSchema: z.ZodType<
    ExecutePolicyWithInputResponse,
    z.ZodTypeDef,
    unknown
> = z
    .object({
        HttpMeta: components.HTTPMetadata$inboundSchema,
        SuccessfulPolicyResponse: components.SuccessfulPolicyResponse$inboundSchema.optional(),
        Headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            HttpMeta: "httpMeta",
            SuccessfulPolicyResponse: "successfulPolicyResponse",
            Headers: "headers",
        });
    });

/** @internal */
export type ExecutePolicyWithInputResponse$Outbound = {
    HttpMeta: components.HTTPMetadata$Outbound;
    SuccessfulPolicyResponse?: components.SuccessfulPolicyResponse$Outbound | undefined;
    Headers: { [k: string]: Array<string> };
};

/** @internal */
export const ExecutePolicyWithInputResponse$outboundSchema: z.ZodType<
    ExecutePolicyWithInputResponse$Outbound,
    z.ZodTypeDef,
    ExecutePolicyWithInputResponse
> = z
    .object({
        httpMeta: components.HTTPMetadata$outboundSchema,
        successfulPolicyResponse: components.SuccessfulPolicyResponse$outboundSchema.optional(),
        headers: z.record(z.array(z.string())),
    })
    .transform((v) => {
        return remap$(v, {
            httpMeta: "HttpMeta",
            successfulPolicyResponse: "SuccessfulPolicyResponse",
            headers: "Headers",
        });
    });

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace ExecutePolicyWithInputResponse$ {
    /** @deprecated use `ExecutePolicyWithInputResponse$inboundSchema` instead. */
    export const inboundSchema = ExecutePolicyWithInputResponse$inboundSchema;
    /** @deprecated use `ExecutePolicyWithInputResponse$outboundSchema` instead. */
    export const outboundSchema = ExecutePolicyWithInputResponse$outboundSchema;
    /** @deprecated use `ExecutePolicyWithInputResponse$Outbound` instead. */
    export type Outbound = ExecutePolicyWithInputResponse$Outbound;
}
