/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import dotenv from "dotenv";
dotenv.config();
/**
 * Example usage of the @styra/opa SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx executeDefaultPolicyWithInput.ts
 */

import { OpaApiClient } from "@styra/opa";

const opaApiClient = new OpaApiClient();

async function main() {
  const result = await opaApiClient.executeDefaultPolicyWithInput({
    "user": "alice",
    "action": "read",
    "object": "id123",
    "type": "dog",
  });

  console.log(result);
}

main().catch(console.error);
