/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../../lib/primitives.js";
import * as components from "../components/index.js";
import { OpaAPIClientError } from "./opaapiclienterror.js";

/**
 * Server Error. All requests returned a 500 error.
 *
 * @remarks
 */
export type BatchServerErrorData = {
  batchDecisionId?: string | undefined;
  responses?: { [k: string]: components.ServerError } | undefined;
};

/**
 * Server Error. All requests returned a 500 error.
 *
 * @remarks
 */
export class BatchServerError extends OpaAPIClientError {
  batchDecisionId?: string | undefined;
  responses?: { [k: string]: components.ServerError } | undefined;

  /** The original data that was passed to this error instance. */
  data$: BatchServerErrorData;

  constructor(
    err: BatchServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    if (err.batchDecisionId != null) this.batchDecisionId = err.batchDecisionId;
    if (err.responses != null) this.responses = err.responses;

    this.name = "BatchServerError";
  }
}

/** @internal */
export const BatchServerError$inboundSchema: z.ZodType<
  BatchServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  batch_decision_id: z.string().optional(),
  responses: z.record(components.ServerError$inboundSchema).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "batch_decision_id": "batchDecisionId",
    });

    return new BatchServerError(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type BatchServerError$Outbound = {
  batch_decision_id?: string | undefined;
  responses?: { [k: string]: components.ServerError$Outbound } | undefined;
};

/** @internal */
export const BatchServerError$outboundSchema: z.ZodType<
  BatchServerError$Outbound,
  z.ZodTypeDef,
  BatchServerError
> = z.instanceof(BatchServerError)
  .transform(v => v.data$)
  .pipe(
    z.object({
      batchDecisionId: z.string().optional(),
      responses: z.record(components.ServerError$outboundSchema).optional(),
    }).transform((v) => {
      return remap$(v, {
        batchDecisionId: "batch_decision_id",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BatchServerError$ {
  /** @deprecated use `BatchServerError$inboundSchema` instead. */
  export const inboundSchema = BatchServerError$inboundSchema;
  /** @deprecated use `BatchServerError$outboundSchema` instead. */
  export const outboundSchema = BatchServerError$outboundSchema;
  /** @deprecated use `BatchServerError$Outbound` instead. */
  export type Outbound = BatchServerError$Outbound;
}
