name: JSR (Manual)

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  jsr:
    name: Publish @styra/opa to JSR
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write # OIDC ID token for authentication with JSR
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
      - name: build and publish @styra/opa to JSR
        run: |
          npm ci
          npm run build --ws
          npx -w packages/opa jsr publish
