name: JSR (Manual)

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  init:
    name: Prereqs
    runs-on: ubuntu-24.04
    steps:
      - uses: StyraOSS/styra-init-action@main # ratchet:exclude

  jsr:
    name: Publish @open-policy-agent/opa to JSR
    runs-on: ubuntu-24.04
    needs: init
    permissions:
      contents: read
      id-token: write # OIDC ID token for authentication with JSR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: 22
      - name: build and publish open-policy-agent/opa to JSR
        run: |
          npm ci
          npm run build --ws
          npx -w packages/opa jsr publish
