name: JSR (Manual)

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  init:
    name: Prereqs
    runs-on: ubuntu-24.04
    steps:
      - uses: StyraInc/styra-init-action@main # ratchet:exclude

  jsr:
    name: Publish @styra/opa to JSR
    runs-on: ubuntu-24.04
    needs: init
    permissions:
      contents: read
      id-token: write # OIDC ID token for authentication with JSR
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 22
      - name: build and publish @styra/opa to JSR
        run: |
          npm ci
          npm run build --ws
          npx -w packages/opa jsr publish
