name: JSR (Manual)

on:
  workflow_dispatch: {}

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  jsr:
    name: Publish @styra/opa to JSR
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write # OIDC ID token for authentication with JSR
    steps:
      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - uses: actions/setup-node@1e60f620b9541d16bece96c5465dc8ee9832be0b # v4.0.3
        with:
          node-version: 21
      - name: publish @styra/opa to JSR
        run: |
          npm ci --foreground-scripts
          npx -w packages/opa jsr publish
