name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  packages:
    name: test packages
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        pkg: [opa-react]
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "21.x"
      - name: setup and test
        run: |
          npm ci
          npm test
        working-directory: packages/${{ matrix.pkg }}
