name: CI

on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
      - main

# When a new revision is pushed to a PR, cancel all in-progress CI runs for that
# PR. See https://docs.github.com/en/actions/using-jobs/using-concurrency
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  init:
    runs-on: ubuntu-22.04
    outputs:
      packages: ${{ steps.workspaces.outputs.packages }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
      - id: workspaces
        run: |
          npm ci
          echo packages=$(npm query .workspace | jq -c '[.[].location]') >> $GITHUB_OUTPUT

  packages:
    name: test packages
    runs-on: ubuntu-22.04
    needs:
      - init
    strategy:
      fail-fast: false
      matrix:
        pkg: ${{ fromJSON(needs.init.outputs.packages) }}
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: 22
      - name: setup and build
        # https://github.com/npm/cli/issues/3034#issuecomment-885211061
        run: |
          npm ci
          npm run build --ws
      - name: test
        run: npx -w ${{ matrix.pkg }} tsx --test ./tests/**/*.ts
        env:
          EOPA_LICENSE_KEY: ${{ secrets.EOPA_LICENSE_KEY }} # @styra/opa needs this
        if: matrix.pkg == 'packages/opa'
      - name: test
        run: npm run -w ${{ matrix.pkg }} --if-present test
      - name: docs
        run: npx -w ${{ matrix.pkg }} --if-present typedoc
      - name: are the types wrong?
        run: npx -w ${{ matrix.pkg }} attw --pack
        if: matrix.pkg != 'packages/opa'
      - name: are the types wrong? (opa)
        run: npx -w ${{ matrix.pkg }} attw --pack --ignore-rules no-resolution
        if: matrix.pkg == 'packages/opa'
      - name: jsr publish dry-run
        run: npx -w ${{ matrix.pkg }} jsr publish --dry-run
        if: matrix.pkg == 'packages/opa'

  success:
    name: tests succeed
    runs-on: ubuntu-22.04
    needs:
      - packages
    steps:
      - run: echo yay
